version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - onepiece

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - onepiece

  application:
    image: ${DOCKER_USERNAME}/onepiece-api:latest
    container_name: application
    ports:
      - "${DOCKER_ONEPIECE_API_PORT}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - onepiece

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - "${DOCKER_ONEPIECE_REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - onepiece

  mongo1:
    image: mongo:8
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo1data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - onepiece

  mongo2:
    image: mongo:8
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - ./mongo2data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - onepiece

  mongo3:
    image: mongo:8
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - ./mongo3data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - onepiece

networks:
  onepiece:
    external: true