version: '3.8'

services:
  nginx:
    image: nginx
    container_name: onepiece-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - onepiece-network

  onepiece-api:
    image: ${DOCKER_USERNAME}/onepiece-api:latest
    container_name: onepiece-api
    ports:
      - "${DOCKER_ONEPIECE_API_PORT}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - onepiece-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - "${DOCKER_ONEPIECE_REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - onepiece-network

  mongo1:
    image: mongo:8
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo1data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - onepiece-network

  mongo2:
    image: mongo:8
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - ./mongo2data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - onepiece-network
  mongo3:
    image: mongo:8
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - ./mongo3data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - onepiece-network
networks:
  onepiece-network:
    driver: bridge