version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: onepiece-prometheus
    user: "$UID:$GID"
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:latest
    ports:
      - "${LOKI_PORT}:3100"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: onepiece-grafana
    user: "$UID:$GID"
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    depends_on:
      - prometheus
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  grafana_storage: {}