version: '3.8'

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--storage.path=/var/lib/alloy/data",
        "/etc/alloy/config.alloy"
      ]
    ports:
      - "12345:12345"
    restart: unless-stopped
    networks:
      - onepiece

networks:
  onepiece:
    external: true

