spring:
  security:
    login-url: ${LOGIN_URL}
    redirect-url: ${REDIRECT_URL}
    cookie:
      domain: ${COOKIE_DOMAIN}
      secure: ${COOKIE_SECURE}
      http-only: ${COOKIE_HTTP_ONLY:false}
    jwt:
      secret_key: ${JWT_SECRET_KEY}
      expiration-time:
        access-token: ${JWT_EXPIRATION_TIME_ACCESS_TOKEN:3600}
        refresh-token: ${JWT_EXPIRATION_TIME_REFRESH_TOKEN:86400}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
            authorization-grant-type: authorization_code

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:50MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  server-url: ${SERVER_URL:localhost}
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

chatgpt:
  api-key: ${CHATGPT_API_KEY}
  model: "gpt-4-mini"
  temperature: 0.7
  maxTokens: 4096

cloud:
  ncp:
    object-storage:
      endpoint: "https://kr.object.ncloudstorage.com"
      credentials:
        access-key: ${NCP_ACCESS_KEY}
        secret-key: ${NCP_SECRET_KEY}
        bucket: ${NCP_BUCKET_NAME}
    region:
      auto: false
      static-region: "ap-southeast-2"
    stack:
      auto: false

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}
  algorithm: ${ENCRYPTION_ALGORITHM}
