springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
chatgpt:
  api-key: "your-api-key-here"
  model: "gpt-4"
  temperature: 0.7
  maxTokens: 4096
