name: "✨ [Feat] 이슈 내용"
description: "새로운 기능이나 개선 사항을 제안하세요."
labels: ["feat"]
assignees: []

body:
  - type: textarea
    id: issue-content
    attributes:
      label: "✨ 이슈 내용"
      description: "여기에 이슈에 대한 설명을 작성하세요."
      placeholder: "이슈에 대한 상세한 내용을 입력하세요."
      value: "이슈를 간략하게 설명하세요."

  - type: checkboxes
    id: work-content
    attributes:
      label: "💡 작업 내용"
      description: "해당 이슈를 해결하기 위한 작업 목록입니다."
      options:
        - label: "작업 1"
        - label: "작업 2"

  - type: textarea
    id: additional-notes
    attributes:
      label: "📌 참고 사항"
      description: "추가적인 참고 사항을 입력하세요."
      placeholder: "관련 문서 링크나 기타 정보를 입력하세요."
      value: "참고할 사항이 있으면 여기에 작성하세요."
