name: Build Check on Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: build without test
        run: ./gradlew compileJava